// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKP_e5smN7Caso79iE7LfArAW16D9H1W4',
    appId: '1:940227783128:android:ff5a938487843531456aad',
    messagingSenderId: '940227783128',
    projectId: 'quiz-app-new-da9c7',
    storageBucket: 'quiz-app-new-da9c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVqzq06TiDfZ83utg2trgO3TXZ3uWQTE',
    appId: '1:940227783128:web:376be33fd8ed0044456aad',
    messagingSenderId: '940227783128',
    projectId: 'quiz-app-new-da9c7',
    authDomain: 'quiz-app-new-da9c7.firebaseapp.com',
    storageBucket: 'quiz-app-new-da9c7.firebasestorage.app',
    measurementId: 'G-NR8ELH47DK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKP_e5smN7Caso79iE7LfArAW16D9H1W4',
    appId: '1:940227783128:android:ff5a938487843531456aad',
    messagingSenderId: '940227783128',
    projectId: 'quiz-app-new-da9c7',
    storageBucket: 'quiz-app-new-da9c7.firebasestorage.app',
    iosBundleId: 'com.example.quizeApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKP_e5smN7Caso79iE7LfArAW16D9H1W4',
    appId: '1:940227783128:android:ff5a938487843531456aad',
    messagingSenderId: '940227783128',
    projectId: 'quiz-app-new-da9c7',
    storageBucket: 'quiz-app-new-da9c7.firebasestorage.app',
    iosBundleId: 'com.example.quizeApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtVqzq06TiDfZ83utg2trgO3TXZ3uWQTE',
    appId: '1:940227783128:web:376be33fd8ed0044456aad',
    messagingSenderId: '940227783128',
    projectId: 'quiz-app-new-da9c7',
    authDomain: 'quiz-app-new-da9c7.firebaseapp.com',
    storageBucket: 'quiz-app-new-da9c7.firebasestorage.app',
    measurementId: 'G-NR8ELH47DK',
  );
}
