// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8xIqsLd8sWwpiJ074R35QSK5NdKVBbAg',
    appId: '1:532212759054:web:3bac875c5e6821f80e9a5f',
    messagingSenderId: '532212759054',
    projectId: 'quiz-app-26f96',
    authDomain: 'quiz-app-26f96.firebaseapp.com',
    storageBucket: 'quiz-app-26f96.firebasestorage.app',
    measurementId: 'G-0JTXCR1Z5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBx6BSmDOhnNvXBRjUK1RXPuEOFLKCIz4',
    appId: '1:532212759054:android:6a17a6dc6c3d474e0e9a5f',
    messagingSenderId: '532212759054',
    projectId: 'quiz-app-26f96',
    storageBucket: 'quiz-app-26f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkeHnwir22cHxcRjADGwHjMRL3-4PeK0',
    appId: '1:532212759054:ios:5feb5ec7315395310e9a5f',
    messagingSenderId: '532212759054',
    projectId: 'quiz-app-26f96',
    storageBucket: 'quiz-app-26f96.firebasestorage.app',
    iosBundleId: 'com.example.quizeApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkeHnwir22cHxcRjADGwHjMRL3-4PeK0',
    appId: '1:532212759054:ios:5feb5ec7315395310e9a5f',
    messagingSenderId: '532212759054',
    projectId: 'quiz-app-26f96',
    storageBucket: 'quiz-app-26f96.firebasestorage.app',
    iosBundleId: 'com.example.quizeApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8xIqsLd8sWwpiJ074R35QSK5NdKVBbAg',
    appId: '1:532212759054:web:8047d8b55c35b5dd0e9a5f',
    messagingSenderId: '532212759054',
    projectId: 'quiz-app-26f96',
    authDomain: 'quiz-app-26f96.firebaseapp.com',
    storageBucket: 'quiz-app-26f96.firebasestorage.app',
    measurementId: 'G-J0J20JWWZG',
  );

}